server:
  port: 8080

spring:
  application:
    name: chewy-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        namespace: chewy-pet
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://chewy-user-service
          predicates:
            - Path=/api/auth/**, /api/user/**
        - id: product-service
          uri: lb://chewy-product-service
          predicates:
            - Path=/api/products/**, /api/categories/**
        - id: order-service
          uri: lb://chewy-order-service
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: lb://chewy-payment-service
          predicates:
            - Path=/api/payment/**
        - id: cart-service
          uri: lb://chewy-cart-service
          predicates:
            - Path=/api/cart/**
        - id: admin-product-service
          uri: lb://chewy-product-service
          predicates:
            - Path=/api/admin/products/**
        - id: admin-service
          uri: lb://chewy-admin-service
          predicates:
            - Path=/api/admin/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
